FROM python:3.12-slim

RUN apt-get update
RUN apt-get upgrade

RUN pip install --upgrade pip

RUN git clone https://github.com/sekrel//weather_forecast

WORKDIR /weather_forecast

RUN pip install -r requirements.txt
RUN python manage.py runserver
