FROM python:3.12

RUN apt-get update
RUN apt-get upgrade -y

ENV PYTHONUNBUFFERED=1

RUN git clone https://github.com/sekrel/weather_forecast

WORKDIR /weather_forecast

RUN pip install -r requirements.txt

EXPOSE 8000
ENTRYPOINT ["python", "./weather_forecast/manage.py"]
CMD ["runserver", "0.0.0.0:8000"]